services:
  - type: web
    name: tona-ai
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /ping
    healthCheckTimeout: 300
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
