services:
  - type: web
    name: tona-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /ping
    healthCheckTimeout: 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
